spring.application.name=hospital-platform

spring.datasource.url=jdbc:postgresql://localhost:5433/hospitaldb
spring.datasource.username=hospitaluser
spring.datasource.password=hospitalpassword

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.flyway.enabled=true
