CREATE TABLE diagnoses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medical_record_id BIGINT NOT NULL,
    description VARCHAR(500) NOT NULL,

    CONSTRAINT fk_diagnosis_medical_record
        FOREIGN KEY (medical_record_id)
        REFERENCES medical_records (id)
);

CREATE INDEX idx_diagnoses_medical_record_id
    ON diagnoses (medical_record_id);
