CREATE TABLE prescriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    medical_record_id BIGINT NOT NULL,
    medication VARCHAR(200) NOT NULL,
    dosage VARCHAR(100) NOT NULL,
    instructions VARCHAR(500) NOT NULL,

    CONSTRAINT fk_prescription_medical_record
        FOREIGN KEY (medical_record_id)
        REFERENCES medical_records (id)
);

CREATE INDEX idx_prescriptions_medical_record_id
    ON prescriptions (medical_record_id);
